# Generated by Django 5.0.6 on 2024-07-30 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_tguser_delete_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tguser',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='tguser',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='tguser',
            name='last_name',
        ),
    ]
