# Generated by Django 5.0.6 on 2024-07-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_tguser_name_alter_tguser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='telegram_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
